# Amsterda urban studies

In [4]:
import pandas as pd
import requests

## APIs

### Energy label

#### Endpoint

#### Response

In [5]:
dict = {
    "_embedded": {
        "energielabel": [
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1011PG~171~~~~0363010001011891~",
                        "title": "20160601~1011PG~171~~~~0363010001011891~",
                        "id": "20160601~1011PG~171~~~~0363010001011891~"
                    }
                },
                "id": "20160601~1011PG~171~~~~0363010001011891~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "1Rgielabel.nl",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1011PG",
                "huisnummer": 171,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010001011891",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2002,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "1,21",
                "energieindexMetEmgForfaitair": "1,21",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2796,08",
                "berekendeEnergieverbruik": "52754,00"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1015JJ~7~2~~~0363010000647799~",
                        "title": "20160601~1015JJ~7~2~~~0363010000647799~",
                        "id": "20160601~1015JJ~7~2~~~0363010000647799~"
                    }
                },
                "id": "20160601~1015JJ~7~2~~~0363010000647799~",
                "registratiedatum": "2016-06-02",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Innax Bouwkundig adviseurs BV",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1015JJ",
                "huisnummer": 7,
                "huisletter": "",
                "huisnummertoevoeging": "2",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000647799",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1905,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "1,39",
                "energieindexMetEmgForfaitair": "1,39",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1883,73",
                "berekendeEnergieverbruik": "36381,54"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1015NG~177~1~~~0363010000954233~",
                        "title": "20160601~1015NG~177~1~~~0363010000954233~",
                        "id": "20160601~1015NG~177~1~~~0363010000954233~"
                    }
                },
                "id": "20160601~1015NG~177~1~~~0363010000954233~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Eneco installatiebedrijven",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1015NG",
                "huisnummer": 177,
                "huisletter": "",
                "huisnummertoevoeging": "1",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000954233",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1930,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "F",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "116814,21"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1015XT~48~H~~~0363010000736175~",
                        "title": "20160601~1015XT~48~H~~~0363010000736175~",
                        "id": "20160601~1015XT~48~H~~~0363010000736175~"
                    }
                },
                "id": "20160601~1015XT~48~H~~~0363010000736175~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Mijnbouwhulp.nl",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenvloer",
                "sbicode": "",
                "postcode": "1015XT",
                "huisnummer": 48,
                "huisletter": "",
                "huisnummertoevoeging": "H",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000736175",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1930,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "D",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "67499,07"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NM~144~~A~~0363010012094717~",
                        "title": "20160601~1018NM~144~~A~~0363010012094717~",
                        "id": "20160601~1018NM~144~~A~~0363010012094717~"
                    }
                },
                "id": "20160601~1018NM~144~~A~~0363010012094717~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussenvloer",
                "sbicode": "",
                "postcode": "1018NM",
                "huisnummer": 144,
                "huisletter": "A",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094717",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,13",
                "energieindexMetEmgForfaitair": "1,13",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1801,83",
                "berekendeEnergieverbruik": "33671,96"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NM~144~~C~~0363010012094719~",
                        "title": "20160601~1018NM~144~~C~~0363010012094719~",
                        "id": "20160601~1018NM~144~~C~~0363010012094719~"
                    }
                },
                "id": "20160601~1018NM~144~~C~~0363010012094719~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1018NM",
                "huisnummer": 144,
                "huisletter": "C",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094719",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,13",
                "energieindexMetEmgForfaitair": "1,13",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1289,54",
                "berekendeEnergieverbruik": "23723,78"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NM~144~~D~~0363010012094720~",
                        "title": "20160601~1018NM~144~~D~~0363010012094720~",
                        "id": "20160601~1018NM~144~~D~~0363010012094720~"
                    }
                },
                "id": "20160601~1018NM~144~~D~~0363010012094720~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1018NM",
                "huisnummer": 144,
                "huisletter": "D",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094720",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,01",
                "energieindexMetEmgForfaitair": "1,01",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1725,53",
                "berekendeEnergieverbruik": "32151,12"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NN~148~~B~~0363010012094723~",
                        "title": "20160601~1018NN~148~~B~~0363010012094723~",
                        "id": "20160601~1018NN~148~~B~~0363010012094723~"
                    }
                },
                "id": "20160601~1018NN~148~~B~~0363010012094723~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1018NN",
                "huisnummer": 148,
                "huisletter": "B",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094723",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,10",
                "energieindexMetEmgForfaitair": "1,10",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "1801,46",
                "berekendeEnergieverbruik": "33477,03"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018NN~148~~D~~0363010012094725~",
                        "title": "20160601~1018NN~148~~D~~0363010012094725~",
                        "id": "20160601~1018NN~148~~D~~0363010012094725~"
                    }
                },
                "id": "20160601~1018NN~148~~D~~0363010012094725~",
                "registratiedatum": "2016-06-14",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Eigen Haard",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1018NN",
                "huisnummer": 148,
                "huisletter": "D",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010012094725",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1880,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "1,07",
                "energieindexMetEmgForfaitair": "1,07",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2942,61",
                "berekendeEnergieverbruik": "55266,27"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1018TZ~44~~~~0363010000673388~",
                        "title": "20160601~1018TZ~44~~~~0363010000673388~",
                        "id": "20160601~1018TZ~44~~~~0363010000673388~"
                    }
                },
                "id": "20160601~1018TZ~44~~~~0363010000673388~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Energielabel Hofstad",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekdak",
                "sbicode": "",
                "postcode": "1018TZ",
                "huisnummer": 44,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000673388",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1985,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "74612,91"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1019GW~41~~~~0363010001162986~",
                        "title": "20160601~1019GW~41~~~~0363010001162986~",
                        "id": "20160601~1019GW~41~~~~0363010001162986~"
                    }
                },
                "id": "20160601~1019GW~41~~~~0363010001162986~",
                "registratiedatum": "2016-06-03",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Innax Bouwkundig adviseurs BV",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1019GW",
                "huisnummer": 41,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010001162986",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2004,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "0,93",
                "energieindexMetEmgForfaitair": "0,93",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "3522,95",
                "berekendeEnergieverbruik": "57470,56"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1019HD~105~~~~0363010001038167~",
                        "title": "20160601~1019HD~105~~~~0363010001038167~",
                        "id": "20160601~1019HD~105~~~~0363010001038167~"
                    }
                },
                "id": "20160601~1019HD~105~~~~0363010001038167~",
                "registratiedatum": "2016-06-09",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Duresta Real Estate Solutions BV",
                "opnametype": "",
                "status": "",
                "berekeningstype": "ISSO75.3, versie 3.0, oktober 2011",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "U",
                "gebouwtype": "",
                "gebouwsubtype": "",
                "sbicode": "81",
                "postcode": "1019HD",
                "huisnummer": 105,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010001038167",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2006,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "0,92",
                "energieindexMetEmgForfaitair": "0,92",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "45,85",
                "berekendeEnergieverbruik": "610,20"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1019LG~465~~~~0363010000953261~",
                        "title": "20160601~1019LG~465~~~~0363010000953261~",
                        "id": "20160601~1019LG~465~~~~0363010000953261~"
                    }
                },
                "id": "20160601~1019LG~465~~~~0363010000953261~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Energetisch- en Bouwkundig Adviesbureau Peters",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekmidden",
                "sbicode": "",
                "postcode": "1019LG",
                "huisnummer": 465,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000953261",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1995,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "52349,89"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1025HT~531~~~~0363010000666241~",
                        "title": "20160601~1025HT~531~~~~0363010000666241~",
                        "id": "20160601~1025HT~531~~~~0363010000666241~"
                    }
                },
                "id": "20160601~1025HT~531~~~~0363010000666241~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "De Label Expert",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekmidden",
                "sbicode": "",
                "postcode": "1025HT",
                "huisnummer": 531,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000666241",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1970,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "F",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "94056,68"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1025MS~54~~~~0363010000981826~",
                        "title": "20160601~1025MS~54~~~~0363010000981826~",
                        "id": "20160601~1025MS~54~~~~0363010000981826~"
                    }
                },
                "id": "20160601~1025MS~54~~~~0363010000981826~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Labelnu",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Rijwoning tussen",
                "gebouwsubtype": "",
                "sbicode": "",
                "postcode": "1025MS",
                "huisnummer": 54,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000981826",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1995,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "B",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "73880,56"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1033EK~10~~~~0363010000880303~",
                        "title": "20160601~1033EK~10~~~~0363010000880303~",
                        "id": "20160601~1033EK~10~~~~0363010000880303~"
                    }
                },
                "id": "20160601~1033EK~10~~~~0363010000880303~",
                "registratiedatum": "2016-06-06",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woning Advies Nederland B.V.",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Maisonnette",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1033EK",
                "huisnummer": 10,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000880303",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1922,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "D",
                "energieindex": "1,87",
                "energieindexMetEmgForfaitair": "1,87",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "4181,87",
                "berekendeEnergieverbruik": "80916,65"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1034NM~42~~~~0363010000893669~",
                        "title": "20160601~1034NM~42~~~~0363010000893669~",
                        "id": "20160601~1034NM~42~~~~0363010000893669~"
                    }
                },
                "id": "20160601~1034NM~42~~~~0363010000893669~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woningstichting Rochdale",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Hoekvloer",
                "sbicode": "",
                "postcode": "1034NM",
                "huisnummer": 42,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000893669",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1977,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "1,50",
                "energieindexMetEmgForfaitair": "1,50",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2673,24",
                "berekendeEnergieverbruik": "50582,99"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1036KL~26~~~~0363010011211107~",
                        "title": "20160601~1036KL~26~~~~0363010011211107~",
                        "id": "20160601~1036KL~26~~~~0363010011211107~"
                    }
                },
                "id": "20160601~1036KL~26~~~~0363010011211107~",
                "registratiedatum": "2016-06-01",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Het Labelhuis",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Rekenmethodiek Definitief Energielabel, versie 1.2, 16 september 2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Rijwoning tussen",
                "gebouwsubtype": "",
                "sbicode": "",
                "postcode": "1036KL",
                "huisnummer": 26,
                "huisletter": "",
                "huisnummertoevoeging": "",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010011211107",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 2010,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "A",
                "energieindex": "",
                "energieindexMetEmgForfaitair": "",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "0,00",
                "berekendeEnergieverbruik": "61687,38"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1051HZ~10~1~~~0363010000845715~",
                        "title": "20160601~1051HZ~10~1~~~0363010000845715~",
                        "id": "20160601~1051HZ~10~1~~~0363010000845715~"
                    }
                },
                "id": "20160601~1051HZ~10~1~~~0363010000845715~",
                "registratiedatum": "2016-09-16",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woning Advies Nederland B.V.",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussenmidden",
                "sbicode": "",
                "postcode": "1051HZ",
                "huisnummer": 10,
                "huisletter": "",
                "huisnummertoevoeging": "1",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000845715",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1920,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "1,52",
                "energieindexMetEmgForfaitair": "1,52",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "2312,57",
                "berekendeEnergieverbruik": "44367,32"
            },
            {
                "_links": {
                    "schema": "https://schemas.data.amsterdam.nl/datasets/duurzaamheid/energielabel/v1",
                    "self": {
                        "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel/20160601~1051HZ~10~3~~~0363010000845717~",
                        "title": "20160601~1051HZ~10~3~~~0363010000845717~",
                        "id": "20160601~1051HZ~10~3~~~0363010000845717~"
                    }
                },
                "id": "20160601~1051HZ~10~3~~~0363010000845717~",
                "registratiedatum": "2016-09-16",
                "opnamedatum": "2016-06-01",
                "metingGeldigTot": "2026-06-01",
                "certificaathouder": "Woning Advies Nederland B.V.",
                "opnametype": "",
                "status": "",
                "berekeningstype": "Nader Voorschrift, versie 1.0, 1 februari 2014 met erratalijst dd 03-11-2014",
                "isOpBasisVanReferentieGebouw": "",
                "gebouwklasse": "W",
                "gebouwtype": "Flatwoning (overig)",
                "gebouwsubtype": "Tussendak",
                "sbicode": "",
                "postcode": "1051HZ",
                "huisnummer": 10,
                "huisletter": "",
                "huisnummertoevoeging": "3",
                "detailaanduiding": "",
                "bagVerblijfsobjectId": "0363010000845717",
                "bagLigplaatsId": "",
                "bagStandplaatsId": "",
                "bagPandIds": "",
                "projectnaam": "",
                "projectobject": "",
                "bouwjaar": 1920,
                "gebruiksoppervlakteThermischeZone": "",
                "compactheid": "",
                "energieklasse": "C",
                "energieindex": "1,73",
                "energieindexMetEmgForfaitair": "1,73",
                "eisEnergiebehoefte": "",
                "primaireFossieleEnergie": "",
                "primaireFossieleEnergieEmgForfaitair": "",
                "aandeelHernieuwbareEnergie": "",
                "aandeelHernieuwbareEnergieEmgForfaitair": "",
                "temperatuuroverschrijding": "",
                "warmtebehoefte": "",
                "energiebehoefte": "",
                "eisPrimaireFossieleEnergie": "",
                "eisAandeelHernieuwbareEnergie": "",
                "eisTemperatuuroverschrijding": "",
                "berekendeCo2Emissie": "3117,34",
                "berekendeEnergieverbruik": "60233,39"
            }
        ]
    },
    "_links": {
        "self": {
            "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel"
        },
        "next": {
            "href": "https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel?page=2"
        }
    },
    "page": {
        "number": 1,
        "size": 20
    }
}

In [6]:
dict.keys()

dict_keys(['_embedded', '_links', 'page'])

In [7]:
dict['_embedded'].keys()

dict_keys(['energielabel'])

In [8]:
dict['_embedded']['energielabel'][0].keys()

dict_keys(['_links', 'id', 'registratiedatum', 'opnamedatum', 'metingGeldigTot', 'certificaathouder', 'opnametype', 'status', 'berekeningstype', 'isOpBasisVanReferentieGebouw', 'gebouwklasse', 'gebouwtype', 'gebouwsubtype', 'sbicode', 'postcode', 'huisnummer', 'huisletter', 'huisnummertoevoeging', 'detailaanduiding', 'bagVerblijfsobjectId', 'bagLigplaatsId', 'bagStandplaatsId', 'bagPandIds', 'projectnaam', 'projectobject', 'bouwjaar', 'gebruiksoppervlakteThermischeZone', 'compactheid', 'energieklasse', 'energieindex', 'energieindexMetEmgForfaitair', 'eisEnergiebehoefte', 'primaireFossieleEnergie', 'primaireFossieleEnergieEmgForfaitair', 'aandeelHernieuwbareEnergie', 'aandeelHernieuwbareEnergieEmgForfaitair', 'temperatuuroverschrijding', 'warmtebehoefte', 'energiebehoefte', 'eisPrimaireFossieleEnergie', 'eisAandeelHernieuwbareEnergie', 'eisTemperatuuroverschrijding', 'berekendeCo2Emissie', 'berekendeEnergieverbruik'])

#### Potential hypothesis

In [9]:
dict['_links'].keys()

dict_keys(['self', 'next'])

In [10]:
dict['_links']['self']

{'href': 'https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel'}

In [11]:
dict['_links']['next']

{'href': 'https://api.data.amsterdam.nl/v1/duurzaamheid/energielabel?page=2'}

### Municipal real estate - Gemeentelijk vastgoed

#### Endpoint

https://data.amsterdam.nl/catalogus/65

In [12]:
url="https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten"
response_municipal = requests.get(url)
print(response_municipal.status_code)

200


#### Response

In [13]:
response_municipal.content

b'{\n  "_embedded":{\n  "gebouwobjecten":[\n  {"_links":{"schema":"https://schemas.data.amsterdam.nl/datasets/gemeentelijk_vastgoed/gebouwobjecten/v1","self":{"href":"https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten/339","title":"339","objectId":339}},"objectId":339,"straatnaam":"Aldebaranplein","huisnummer":null,"huisletter":null,"huisnummertoevoeging":"2-4","huisnummeraanduiding":null,"eigendom":"Volle eigendom","bagPandIds":["0363100012062051"],"geometrie":{"type":"MultiPolygon","coordinates":[[[[121372.063,491634.878],[121376.943,491631.063],[121391.455,491649.607],[121387.537,491652.685],[121388.672,491654.135],[121384.725,491657.232],[121384.585,491657.342],[121372.794,491642.255],[121370.318,491644.189],[121369.794,491643.519],[121367.381,491645.403],[121367.311,491645.314],[121356.804,491631.911],[121354.963,491633.353],[121353.057,491630.911],[121345.047,491637.161],[121344.739,491636.744],[121344.487,491636.933],[121344.22,491637.099],[121343.94,491637

In [14]:
info_municipal = response.json()
info_municipal

NameError: name 'response' is not defined

In [ ]:
type(info_municipal)

In [ ]:
info_municipal.keys()

In [ ]:
info_municipal['_embedded'].keys()

In [ ]:
info_municipal['_embedded']['gebouwobjecten'][0].keys()

#### Finding

**No postcode**

### Building -gebouwobjecten

#### Endpoint

In [ ]:
url_buildingobject="https://api.data.amsterdam.nl/v1/gemeentelijk_vastgoed/v2/gebouwobjecten"
response_buildingobject = requests.get(url_buildingobject)
print(response_buildingobject.status_code)

#### Response

In [ ]:
info_buildingobject = response_buildingobject.json()
info_buildingobject

In [ ]:
info_buildingobject.keys()

In [ ]:
info_buildingobject['_embedded']['gebouwobjecten'][0]

### Markets

#### Endpoint

In [ ]:
404

### Basic Register of Addresses and Buildings - (BAG) Basisregistratie adressen en gebouwen (BAG)

#### Endpoint

In [ ]:
url_bag="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres"
response_bag = requests.get(url_bag)
print(response_bag.status_code)

#### Response

In [ ]:
info_bag = response_bag.json()
info_bag

In [ ]:
info_bag['_embedded'].keys()

In [ ]:
info_bag['_embedded']['verblijfsobjecten'][0].keys()

In [ ]:
info_bag['_embedded']['heeftHoofdadres'][0].keys()

#### Iteration through pages

In [ ]:

# This variable starts with the same value as we had for url_bag,
# but will change as the code goes throuh the pages:
headers = {
    "X-Api-Key": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OTk2Mzk2MTk0MTcyNjEwNjM1IiwiZXhwIjoxODE0MzU1ODQ1fQ.LfXJNucSt2nDBrgA60ElAZdpz89--auFrCQbU3Re17e-MYHeZhBPc34x0nVxc-Ri4xCB0LuiST2UDmZnaOnnAg"
}
url_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres"

all_records_heeftHoofdadres = []
page = 1

while url_pagination:

    print(f"Downloading page {page}")

    response_page = requests.get(url_pagination)
    response_page.raise_for_status()

    info_page = response_page.json()

    # Add the records from this page
    all_records_heeftHoofdadres.extend(info_page["_embedded"]["heeftHoofdadres"])

    # Get the URL for the next page (if any)
    url_pagination = info_page["_links"].get("next", {}).get("href")

    page += 1
    

In [ ]:
info_page["_links"]

In [ ]:

url_pagination

In [ ]:
headers = {
    "X-Api-Key": "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OTk2Mzk2MTk0MTcyNjEwNjM1IiwiZXhwIjoxODE0MzU1ODQ1fQ.LfXJNucSt2nDBrgA60ElAZdpz89--auFrCQbU3Re17e-MYHeZhBPc34x0nVxc-Ri4xCB0LuiST2UDmZnaOnnAg"
}

url_test_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&page=101"
url_test2_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?_expandScope=heeftHoofdadres&_pageSize=100&_count=true"
url_test3_pagination="https://api.data.amsterdam.nl/v1/bag/verblijfsobjecten?page=101"


response_test_page = requests.get(url_test3_pagination, headers=headers)
print(response_test_page.status_code)

In [ ]:
response_test_page_object= response_test_page.json()

In [ ]:
response_test_page_object['page']['totalPages']

In [ ]:
response_test_page_object["page"]["totalElements"]

#### Transform to Data Frame

In [ ]:
len(all_records_heeftHoofdadres)

In [ ]:
municipal_bag_data = pd.DataFrame(all_records_heeftHoofdadres)

In [ ]:
municipal_bag_data

In [ ]:
municipal_bag_data['postcode'].unique()

In [ ]:
found_postCode = municipal_bag_data['postcode'].unique()

In [ ]:
type(found_postCode[1])

In [ ]:
found_postCode = [
    postcode[:4] if isinstance(postcode, str) else postcode
    for postcode in found_postCode
]
found_postCode

In [ ]:
unique_postcodes = set(found_postCode)
len(unique_postcodes)

In [ ]:
unique_postcodes 

### Trash

Distance from homes to trash deposits - Loopafstanden

In [ ]:
Service areas - trash

In [ ]:
https://data.amsterdam.nl/catalogus/55

#### Tests

In [ ]:
url_test1_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container"
url_test2_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?&_pageSize=100&_count=true"
url_test3_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?fractieCode=2&_pageSize=100&_count=true"


response_test3_trash = requests.get(url_test3_trash)
print(response_test3_trash.status_code)
response_test3_trash_object= response_test3_trash.json()
response_test3_trash_object

In [ ]:
response_test_trash_object["page"]['totalPages']

In [ ]:
response_test_trash_object["page"]["totalElements"]

In [ ]:
response_test3_trash_object["page"]['totalPages']

In [ ]:
response_test3_trash_object["page"]["totalElements"]

#### Response

In [ ]:
url_trash="https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?fractieCode=2"

response_trash = requests.get(url_trash)
print(response_trash.status_code)

info_trash = response_trash.json()
info_trash

In [ ]:
info_trash['_embedded'].keys()

In [ ]:
len(info_trash['_embedded']['container'])

In [ ]:
info_trash['_embedded']['container'][0]

In [ ]:
info_trash['_embedded']['container'][19]

In [ ]:
info_trash['_embedded']['container'][0]['geometrie']['coordinates']

#### Iteration through pages

In [ ]:
all_records_glass_trash = []
page = 1

url_trash_pagination = "https://api.data.amsterdam.nl/v1/huishoudelijkafval/container?fractieCode=2&_pageSize=100"

while url_trash_pagination:

    print(f"Downloading page {page}")

    response_page = requests.get(url_trash_pagination)
    response_page.raise_for_status()

    info_page = response_page.json()

    embedded = info_page["_embedded"]
    collection = next(iter(embedded))

    missing_geometry = 0
    for container in embedded[collection]:
        geometrie = container.get("geometrie")
        if geometrie is None:
            missing_geometry += 1
            continue
        if geometrie and "coordinates" in geometrie:
            all_records_glass_trash.append(geometrie["coordinates"])
    
    # Get the URL for the next page (if any)
    url_trash_pagination = info_page["_links"].get("next", {}).get("href")
    print(url_trash_pagination)

    page += 1

In [ ]:
url_pagination = info_page["_links"].get("next", {}).get("href")
url_pagination

#### Transform to Data Frame¶

In [ ]:
len(all_records_glass_trash)

In [ ]:
glass_trash_data = pd.DataFrame(all_records_glass_trash)

In [ ]:
glass_trash_data

In [ ]:
glass_trash_data['object'] = 'glass_trash_can'

In [ ]:
glass_trash_data = glass_trash_data[['object', 0, 1]]

In [ ]:
glass_trash_data

In [ ]:
glass_trash_data.to_csv('glass_trash_api.csv')

## CSV

#### Load dataframe

In [15]:
housing_units = pd.read_csv(
    "BAG_verblijfsobject_Actueel.csv",
    sep=";",
    low_memory=False
)

In [16]:
housing_units.head()

,identificatie,aanduidingInOnderzoek,geconstateerd,heeftIn:BAG.NAG.identificatieHoofdadres,huisnummerHoofdadres,huisletterHoofdadres,huisnummertoevoegingHoofdadres,postcodeHoofdadres,ligtAan:BAG.ORE.identificatieHoofdadres,ligtAan:BAG.ORE.naamHoofdadres,...,ligtIn:GBD.GGW.code,ligtIn:GBD.GGW.naam,ligtIn:GBD.GGP.identificatie,ligtIn:GBD.GGP.code,ligtIn:GBD.GGP.naam,ligtIn:GBD.SDL.identificatie,ligtIn:GBD.SDL.code,ligtIn:GBD.SDL.naam,geometrie,bagproces
0,363010000543292,N,N,363200000006110,1,NaN,H,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120700 487936),NaN
1,363010000543300,N,N,363200000006119,5,NaN,1,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120703 487926),Muteren naar aanleiding van signalering
2,363010000543305,N,N,363200000006124,7,NaN,2,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120705 487922),Muteren naar aanleiding van signalering
3,363010000543308,N,N,363200000403263,17,NaN,NaN,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120709 487918),Muteren naar aanleiding van signalering
4,363010000543318,N,N,363200000006133,29,NaN,NaN,1015NR,363300000002529,Eerste Anjeliersdwarsstraat,...,GA01,Centrum-West,NaN,NaN,NaN,3630000000018,A,Centrum,POINT (120708 487907),Muteren naar aanleiding van signalering


In [17]:
housing_units.info()

<class 'pandas.DataFrame'>
RangeIndex: 582145 entries, 0 to 582144
Data columns (total 55 columns):
 #   Column                                   Non-Null Count   Dtype  
---  ------                                   --------------   -----  
 0   identificatie                            582145 non-null  int64  
 1   aanduidingInOnderzoek                    582145 non-null  str    
 2   geconstateerd                            582145 non-null  str    
 3   heeftIn:BAG.NAG.identificatieHoofdadres  582145 non-null  int64  
 4   huisnummerHoofdadres                     582145 non-null  int64  
 5   huisletterHoofdadres                     114673 non-null  str    
 6   huisnummertoevoegingHoofdadres           186805 non-null  str    
 7   postcodeHoofdadres                       572341 non-null  str    
 8   ligtAan:BAG.ORE.identificatieHoofdadres  582145 non-null  int64  
 9   ligtAan:BAG.ORE.naamHoofdadres           582145 non-null  str    
 10  ligtIn:BAG.WPS.identificatieHoofdadres   58

In [18]:
housing_units.shape

(582145, 55)

In [20]:
housing_units['postcodeHoofdadres'].nunique()

19136

In [27]:
housing_units['postNumber']=housing_units['postcodeHoofdadres'].str[:4]

In [28]:
housing_units['postNumber'].head()

0    1015
1    1015
2    1015
3    1015
4    1015
Name: postNumber, dtype: str

In [32]:
housing_units['postNumber'].value_counts()

postNumber
1102    17255
1018    15297
1013    14865
1019    12402
1055    12083
        ...  
1042      216
1045      161
1041      139
1044       41
1037        4
Name: count, Length: 85, dtype: int64

In [33]:
units_per_postcode = housing_units['postNumber'].value_counts()

In [35]:
units_df = pd.DataFrame(units_per_postcode)

In [36]:
units_df

,count
postNumber,
1102,17255
1018,15297
1013,14865
1019,12402
1055,12083
...,...
1042,216
1045,161
1041,139


In [37]:
units_df["count"].sum()

np.int64(572341)

In [38]:
units_df.to_csv('house_units.csv')

In [61]:
units_df = units_df.sort_index()
units_df

,count
postNumber,
1011,7482
1012,9206
1013,14865
1014,4098
1015,11168
...,...
1109,708
1381,2875
1382,6232


In [45]:
postCode_activities=[1383, 1107, 1106, 1381, 1105, 1102, 1108, 1109, 1382, 1104, 1101,
       1096, 1112, 1384, 1103, 1097, 1079, 1111, 1098, 1078, 1091, 1074,
       1092, 1093, 1066, 1081, 1083, 1082, 1062, 1076, 1059, 1075, 1068,
       1069, 1077, 1072, 1073, 1071, 1058, 1054, 1065, 1017, 1018, 1011,
       1060, 1067, 1053, 1012, 1016, 1057, 1052, 1056, 1061, 1064, 1063,
       1055, 1015, 1051, 1013, 1021, 1031, 1014, 1043, 1042, 1041, 1046,
       1044, 1095, 1094, 1019, 1087, 1086, 1023, 1026, 1027, 1028, 1024,
       1022, 1025, 1151, 1032, 1034, 1035, 1047, 1045, 1033, 1036, 1037]
len(postCode_activities)

88

In [55]:
postCode_hunits = set(units_df.index.tolist())
postCode_hunits = [int(x) for x in postCode_hunits if x != ""]
len(postCode_hunits)
print(postCode_hunits)

[1055, 1051, 1094, 1047, 1071, 1028, 1061, 1066, 1383, 1054, 1103, 1057, 1093, 1045, 1102, 1069, 1074, 1087, 1096, 1072, 1012, 1033, 1104, 1064, 1081, 1106, 1082, 1053, 1056, 1091, 1032, 1384, 1036, 1095, 1011, 1014, 1023, 1027, 1382, 1052, 1105, 1077, 1018, 1042, 1075, 1097, 1017, 1059, 1079, 1035, 1031, 1108, 1043, 1046, 1107, 1022, 1024, 1026, 1016, 1068, 1025, 1034, 1067, 1063, 1062, 1060, 1041, 1044, 1021, 1101, 1015, 1078, 1019, 1109, 1058, 1037, 1013, 1083, 1092, 1086, 1098, 1381, 1076, 1065, 1073]


In [57]:
missing_values = [x for x in postCode_activities if x not in postCode_hunits]
len(missing_values)
print(missing_values)

[1112, 1111, 1151]


In [49]:
postCode_hunits = list(postCode_hunits)

In [58]:
housing_units['postLetter']=housing_units['postcodeHoofdadres'].str[4:]

In [59]:
housing_units['postLetter'].head()

0    NR
1    NR
2    NR
3    NR
4    NR
Name: postLetter, dtype: str

## Context

Amsterdam spans approximately 16,748 unique 6-digit postal codes (e.g., 1012 JS). These are distributed across roughly 75 unique 4-digit district areas (e.g., 1012). Each specific 6-digit postcode generally covers an average of just 15 to 20 individual addresses.

https://www.amsterdam.nl/stelselpedia/bag-index/producten-bag/prodspec-postcode/

Postal codes in Amsterdam fall within the 1000 to 1109 range. They are divided across the city's seven main districts and Weesp as follows:

- Centrum (1011 - 1019): Covers the historic inner city, canals, and the Eastern Docklands.
- Noord (1020 - 1039): Situated directly across the IJ river.
- Westpoort (1040 - 1049): Amsterdam's primary port and industrial area.
- West (1050 - 1059): Neighborhoods just west of the Singelgracht.
- Nieuw-West (1060 - 1069): Residential areas extending towards the western outskirts.
- Zuid (1070 - 1083): Includes De Pijp, Oud-Zuid, and the Zuidas business district.
- Oost (1086 - 1099): The eastern residential boroughs.
- Zuidoost (1100 - 1109): The southeastern region, including the Bijlmer and Gaasperplas.
https://nl.wikipedia.org/wiki/Lijst_van_postcodes_1000-1999_in_Nederland